create TABLE EMPLOYEES(
EMPID NUMBER(3),
FIRSTNAME VARCHAR2(20),
LASTNAME VARCHAR2(20),
CITY VARCHAR2(20)
);

INSERT INTO EMPLOYEES VALUES(10,'GEORGE','SMITH','HOWARD');
INSERT INTO EMPLOYEES VALUES(105,'MARY','JONES','LOSANTIVILLE');
INSERT INTO EMPLOYEES VALUES(152,'SAM','TONES','PARIS');
INSERT INTO EMPLOYEES VALUES(215,'SARAH','ACKERMAN','UPTON');
INSERT INTO EMPLOYEES VALUES(244,'MAITHILI','GUPTA','NEW DELHI');
INSERT INTO EMPLOYEES VALUES(300,'ROBERT','SAMUEL','WASHINGTON');
INSERT INTO EMPLOYEES VALUES(335,'HENRY','WILLIAMA','BOSTON');

SELECT CONCAT(CONCAT(FIRSTNAME, ' '), LASTNAME) AS FULLNAME FROM EMPLOYEES;


