create table MANAGERS(
ID NUMBER(2),
NAME VARCHAR2(10),
SALARY NUMBER(6)
);

INSERT INTO MANAGERS VALUES(1,'HARPREET',20000);
INSERT INTO MANAGERS VALUES(2,'RAVI',30000);
INSERT INTO MANAGERS VALUES(3,'VINAY',10000);
INSERT INTO MANAGERS VALUES(4,'RAVI',30000);
INSERT INTO MANAGERS VALUES(5,'HARPREET',20000);
INSERT INTO MANAGERS VALUES(6,'VINAY',10000);
INSERT INTO MANAGERS VALUES(7,'RAJEEV',40000);
INSERT INTO MANAGERS VALUES(8,'VINAY',10000);
INSERT INTO MANAGERS VALUES(9,'RAVI',30000);
INSERT INTO MANAGERS VALUES(10,'SANJAY',50000);

DELETE M1 FROM MANAGERS M1, MANAGERS M2 WHERE (M2.NAME=M1.NAME) AND (M1.ID>M2.ID);
//This query deletes duplicate data from table so that only first data remains constant or
we get only 1 row per person. 