SELECT * FROM
(SELECT EMPID, FIRSTNAME, LASTNAME, CITY, ROWNUM RN FROM JOBS)
WHERE MOD(RN,2)<>2;

SELECT * FROM
(SELECT EMPID, FIRSTNAME, LASTNAME, CITY, ROWNUM RN FROM JOBS)
WHERE MOD(RN,2)<>=;