create table CITY(
PINCODE NUMBER(6),
TOWN VARCHAR2(15),
CITY VARCHAR2(15)
);

INSERT INTO CITY VALUES(110089,'TEHRI','SHIVALIK');
INSERT INTO CITY VALUES(53637,'SANAPUR','DUMDUM');
INSERT INTO CITY VALUES(245362,'KHEMBAD','HOSHIA');
INSERT INTO CITY VALUES(536271,'CHARLO','POKRIAL');
INSERT INTO CITY VALUES(98462,'PRATAPGARH','MAHARANAPUR');
INSERT INTO CITY VALUES(536271,'HAPPA','MEKH');
INSERT INTO CITY VALUES(216731,'BHEEM','KIRMADA');
INSERT INTO CITY VALUES(119807,'KHILJI','JOHAN');

SELECT * FROM CITY ORDER BY LENGTH(CITY) ASC ;
SELECT CITY FROM (SELECT * FROM CITY ORDER BY LENGTH(CITY) ASC) WHERE ROWNUM<2;
SELECT CITY FROM (SELECT * FROM CITY ORDER BY LENGTH(CITY) DESC) WHERE ROWNUM<2;